import { useEffect, useState } from "react";
import { Button } from "@heroui/react";
import { API } from "@/shared/api/client.js";
import { thumbHi } from "@/shared/api/thumbnails.js";
import { CheckCircle, UserCheck, UserPlus } from "@/shared/icons/icons.jsx";
import { useLang } from "@/shared/i18n/context.jsx";
import { RetryingImage } from "@/shared/ui/retrying-image.jsx";

function artistName(artists) {
  if (!Array.isArray(artists)) return artists || "";
  return artists
    .map((artist) => (typeof artist === "string" ? artist : artist?.name || artist?.artist))
    .filter(Boolean)
    .join(", ");
}

function primaryArtistBrowseId(track) {
  return (
    track?.artistBrowseId ||
    track?.artistLinks?.find((artist) => artist?.browseId)?.browseId ||
    (Array.isArray(track?.artists)
      ? track.artists.find((artist) => artist?.browseId || artist?.id)?.browseId ||
        track.artists.find((artist) => artist?.browseId || artist?.id)?.id
      : "")
  );
}

function creditRows(description) {
  if (!description) return [];
  const seen = new Set();
  return description
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !/auto-generated by youtube/i.test(line))
    .filter((line) => {
      const key = line.toLocaleLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map((line) => {
      const colon = line.indexOf(":");
      if (colon > 0 && colon < 42) {
        return { value: line.slice(colon + 1).trim(), role: line.slice(0, colon).trim() };
      }
      return { value: line, role: "" };
    });
}

export function AboutSongDetails({
  track,
  description,
  descriptionError,
  onRetryDescription,
  onOpenArtist,
}) {
  const t = useLang();
  const [artist, setArtist] = useState(null);
  const [artistLoading, setArtistLoading] = useState(true);
  const [subscriptionBusy, setSubscriptionBusy] = useState(false);
  const [showAllCredits, setShowAllCredits] = useState(false);
  const trackArtistName = artistName(track?.artists);

  useEffect(() => {
    if (!track?.videoId) return;
    let cancelled = false;

    const loadArtist = async () => {
      setArtist(null);
      setArtistLoading(true);
      let browseId = primaryArtistBrowseId(track);
      if (!browseId) {
        const metadataResponse = await fetch(`${API}/song/info/${track.videoId}`);
        if (metadataResponse.ok) {
          const metadata = await metadataResponse.json();
          browseId = metadata.artistBrowseId || "";
        }
      }
      if (!browseId) return;
      const artistResponse = await fetch(`${API}/artist/${browseId}`);
      if (!artistResponse.ok) return;
      const artistData = await artistResponse.json();
      if (!cancelled && !artistData.error) setArtist({ ...artistData, browseId });
    };

    loadArtist()
      .catch(() => {})
      .finally(() => {
        if (!cancelled) setArtistLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [track]);

  useEffect(() => setShowAllCredits(false), [track?.videoId]);

  const parsedRows = creditRows(description);
  const rows = trackArtistName
    ? [
        { value: trackArtistName, role: t("primaryArtist") },
        ...parsedRows.filter(
          (row) => row.value.toLocaleLowerCase() !== trackArtistName.toLocaleLowerCase()
        ),
      ]
    : parsedRows;
  const visibleRows = showAllCredits ? rows : rows.slice(0, 4);
  const displayArtist = artist?.name || trackArtistName || t("artist");

  const toggleSubscription = async () => {
    if (!artist?.browseId || subscriptionBusy) return;
    const wasSubscribed = Boolean(artist.subscribed);
    setArtist((current) => ({ ...current, subscribed: !wasSubscribed }));
    setSubscriptionBusy(true);
    try {
      const response = await fetch(
        `${API}/artist/${artist.browseId}/${wasSubscribed ? "unsubscribe" : "subscribe"}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ channelId: artist.channelId || artist.browseId }),
        }
      );
      if (!response.ok) throw new Error("subscription request failed");
    } catch {
      setArtist((current) => ({ ...current, subscribed: wasSubscribed }));
    } finally {
      setSubscriptionBusy(false);
    }
  };

  return (
    <div className="about-song-details">
      <section className="about-song-card about-song-artist">
        <div className="about-song-artist__visual">
          {artist?.thumbnail && (
            <RetryingImage
              src={thumbHi(artist.thumbnail, 720)}
              alt=""
              className="about-song-artist__image"
            />
          )}
          <div className="about-song-artist__scrim" aria-hidden="true" />
          <h3>{t("artistInformation")}</h3>
        </div>
        <div className="about-song-artist__body">
          <div className="about-song-artist__heading">
            <div className="about-song-artist__identity">
              <Button
                variant="ghost"
                isDisabled={!artist?.browseId}
                onPress={() => onOpenArtist?.({ browseId: artist.browseId, artist: displayArtist })}
                className="about-song-artist__link"
              >
                <span className="about-song-artist__name">
                  {displayArtist}
                  {artist?.channelId && <CheckCircle size={14} className="text-accent" />}
                </span>
              </Button>
              {(artist?.monthlyListeners || artist?.subscribers) && (
                <div className="about-song-artist__listeners">
                  {artist.monthlyListeners
                    ? `${artist.monthlyListeners} ${t("monthlyListeners")}`
                    : `${artist.subscribers} ${t("subscribers")}`}
                </div>
              )}
            </div>
            {artist?.browseId && (
              <Button
                variant="secondary"
                size="sm"
                isDisabled={subscriptionBusy}
                onPress={toggleSubscription}
                className="about-song-follow"
              >
                {artist.subscribed ? <UserCheck size={13} /> : <UserPlus size={13} />}
                {artist.subscribed ? t("following") : t("follow")}
              </Button>
            )}
          </div>
          {artistLoading ? (
            <div className="about-song-placeholder">{t("loadingDots")}</div>
          ) : artist?.description ? (
            <p className="about-song-artist__description">{artist.description}</p>
          ) : null}
        </div>
      </section>

      <section className="about-song-card about-song-credits">
        <div className="about-song-card__header">
          <h3>{t("songInformation")}</h3>
          {rows.length > 4 && (
            <Button
              variant="ghost"
              size="sm"
              onPress={() => setShowAllCredits((shown) => !shown)}
              className="about-song-show-all"
            >
              {showAllCredits ? t("showLess") : t("showAll")}
            </Button>
          )}
        </div>

        {description === null && !descriptionError && (
          <div className="about-song-placeholder">{t("loadingDots")}</div>
        )}
        {descriptionError && (
          <div className="about-song-empty">
            <span>{t("noCredits")}</span>
            <Button variant="secondary" size="sm" onPress={onRetryDescription}>
              {t("retry")}
            </Button>
          </div>
        )}
        {description !== null && !descriptionError && rows.length === 0 && (
          <div className="about-song-placeholder">{t("noCredits")}</div>
        )}
        {visibleRows.length > 0 && (
          <div className="about-song-credit-list">
            {visibleRows.map((row, index) => (
              <div className="about-song-credit" key={`${row.value}-${index}`}>
                <div className="about-song-credit__value">{row.value}</div>
                {row.role && <div className="about-song-credit__role">{row.role}</div>}
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
